###
POST http://localhost:8000/user-service/users
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json

{
"email":"dkaskgkdua@naver.com",
"name":"song",
"pwd":"g2"
}

###
GET http://localhost:8000/user-service/users

###
GET http://localhost:8000/user-service/users/d80c192e-2be8-4990-99a3-dacc1f2d5cf3