###
POST {{api-host}}/user-service/users
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json

{
"email":"dkaskgkdua@naver.com",
"name":"song",
"pwd":"g2"
}
### 5eecd261-1947-4b17-8ceb-e8f71c56441f
###
# @no-redirect
POST {{api-host}}/user-service/login

{
"email":"dkaskgkdua@naver.com",
"password":"g2"
}

> {%
client.test("로그인 성공 검증", function() {
   client.assert(response.status === 200,  "로그인 실패");

   client.global.set("token",response.headers.valueOf("token"));
   client.global.set("userId", response.headers.valueOf("userId"));
});
%}

###
GET {{api-host}}/user-service/users

### 유저정보 호출
GET {{api-host}}/user-service/users/{{userId}}
Authorization: Bearer {{token}}

### 주문 추가
POST {{api-host}}/order-service/{{userId}}/orders
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json
Authorization: Bearer {{token}}

{
"productId":"2",
"qty":10,
"unitPrice":5000
}



### healthcheck
GET {{api-host}}/user-service/health_check
Authorization: Bearer {{token}}

### welcome
GET {{api-host}}/user-service/welcome
Authorization: Bearer {{token}}

### actuator refresh
POST http://localhost:8000/user-service/actuator/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYTY3YTU5MS0wNWRkLTQ3NGItODM0ZS0xNDY5OTJmZTk1NWIiLCJleHAiOjE2NzkzMjk3MTV9.VvroN30UDcOfi1o2oSxCQt-tIb_5ojJNL-gQlvUu4W-zheJwu7UY7uaBMwTiWiQwVkr503kMm6YvJfC6v5xaqw

### actuator bus refresh
POST http://localhost:8000/user-service/actuator/busrefresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlYTY3YTU5MS0wNWRkLTQ3NGItODM0ZS0xNDY5OTJmZTk1NWIiLCJleHAiOjE2NzkzMjk3MTV9.VvroN30UDcOfi1o2oSxCQt-tIb_5ojJNL-gQlvUu4W-zheJwu7UY7uaBMwTiWiQwVkr503kMm6YvJfC6v5xaqw

### config encrypt
POST http://localhost:8888/encrypt

user_token_prod

### config decrypt
POST http://localhost:8888/decrypt

972bb7a462be766740dacb2067b66b296bb798fbec7849c66ce3df32b56de59b

### config
GET http://localhost:8888/user-service/default

### config
GET http://localhost:8888/config-service/default

### kafka connect 리스트
GET http://localhost:8083/connectors

### kafka connect 리스트 상세
GET http://localhost:8083/connectors/my-order-sink-connect

### kafka connect 리스트 상세 status
GET http://localhost:8083/connectors/my-order-sink-connect/status


### kafka connect 삭제
DELETE http://localhost:8083/connectors/my-order-sink-connect

### kafka task 재실행
POST http://localhost:8083/connectors/my-order-sink-connect/tasks/0/restart


### kafka connect 생성
POST http://localhost:8083/connectors
Content-Type: application/json

{

    "name" : "my-source-connect",

    "config" : {

        "connector.class" : "io.confluent.connect.jdbc.JdbcSourceConnector",

        "connection.url":"jdbc:mysql://localhost:3306/msa",

        "connection.user":"msa",

        "connection.password":"1234",

        "mode": "incrementing",

        "incrementing.column.name" : "id",

        "table.whitelist":"users",

        "topic.prefix" : "my_topic_",

        "tasks.max" : "1"

    }

}

### kafka connect connect2
POST http://localhost:8083/connectors
Content-Type: application/json

{

  "name" : "my-source-connect-2",

  "config" : {

    "connector.class" : "io.confluent.connect.jdbc.JdbcSourceConnector",

    "connection.url":"jdbc:mysql://localhost:3306/msa",

    "connection.user":"msa",

    "connection.password":"1234",

    "mode": "timestamp+incrementing",

    "timestamp.column.name" : "modified_at",

    "incremental.column.name" : "id",

    "validate.non.null": false,

    "table.whitelist":"users",

    "topic.prefix" : "my_topic_2_",

    "tasks.max" : "1"

  }

}

### kafka order sink connect
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name":"my-order-sink-connect",
  "config":{
      "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
      "connection.url":"jdbc:mysql://localhost:3306/msa",
      "connection.user":"root",
      "connection.password":"1234",
      "auto.create":"true",
      "auto.evolve":"true",
      "delete.enabled":"false",
      "tasks.max":"1",
      "topics":"orders"
  }
}


### kafka sink connect
POST http://localhost:8083/connectors
Content-Type: application/json

{

  "name":"my-sink-connect",

  "config":{

      "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",

      "connection.url":"jdbc:mysql://localhost:3306/msa",

      "connection.user":"msa",

      "connection.password":"1234",

      "auto.create":"true",

      "auto.evolve":"true",

      "delete.enabled":"false",

      "tasks.max":"1",

      "topics":"my_topic_users"

  }

}


### kafka sink connect
POST http://localhost:8083/connectors
Content-Type: application/json

{

  "name":"my-sink-connect2",

  "config":{

      "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",

      "connection.url":"jdbc:mysql://localhost:3306/msa",

      "connection.user":"msa",

      "connection.password":"1234",

      "auto.create":"true",

      "auto.evolve":"true",

      "delete.enabled":"false",

      "tasks.max":"1",

      "topics":"my_topic_2_users"

  }

}

