server:
  port: 8888
# awsDevMJ ????? git repo? ?? ??? ??
# localhost:port/yml???/default
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dkaskgkdua/msa-spring-cloud-config.git
#          private repository 라면...
#          username: [your username]
#          password: [your password]

